name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm install

      - name: 构建项目
        run: npm run build

      - name: 部署到服务器
        uses: root
        with:
          host: 8.154.20.183
          username: root
          password: Cyp123456789
          port: 22
          source: 'dist/*'
          target: '/var/www/html'
